---

- name: ELASTICSEARCH | Manage Debian environment
  import_tasks: debian.yml
  when: ansible_os_family == 'Debian'

- name: ELASTICSEARCH | Configuration
  import_tasks: configure.yml
  tags: configure
